
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(481, 433)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 480, 390))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_up = QtWidgets.QLabel(self.tab)
        self.label_up.setGeometry(QtCore.QRect(0, 0, 480, 360))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.label_up.sizePolicy().hasHeightForWidth())
        self.label_up.setSizePolicy(sizePolicy)
        self.label_up.setText("")
        self.label_up.setObjectName("label_up")
        self.label_down = QtWidgets.QLabel(self.tab)
        self.label_down.setGeometry(QtCore.QRect(350, 0, 128, 96))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.label_down.sizePolicy().hasHeightForWidth())
        self.label_down.setSizePolicy(sizePolicy)
        self.label_down.setObjectName("label_down")
        self.button_save_picture = QtWidgets.QPushButton(self.tab)
        self.button_save_picture.setGeometry(QtCore.QRect(10, 330, 81, 25))
        self.button_save_picture.setMaximumSize(QtCore.QSize(139, 25))
        self.button_save_picture.setObjectName("button_save_picture")
        self.label_color_1 = QtWidgets.QLabel(self.tab)
        self.label_color_1.setGeometry(QtCore.QRect(0, 0, 100, 20))
        self.label_color_1.setText("")
        self.label_color_1.setObjectName("label_color_1")
        self.label_color_2 = QtWidgets.QLabel(self.tab)
        self.label_color_2.setGeometry(QtCore.QRect(0, 20, 100, 20))
        self.label_color_2.setText("")
        self.label_color_2.setObjectName("label_color_2")
        self.label_color_3 = QtWidgets.QLabel(self.tab)
        self.label_color_3.setGeometry(QtCore.QRect(0, 40, 100, 20))
        self.label_color_3.setText("")
        self.label_color_3.setObjectName("label_color_3")
        self.label_depth_1 = QtWidgets.QLabel(self.tab)
        self.label_depth_1.setGeometry(QtCore.QRect(350, 96, 128, 20))
        self.label_depth_1.setText("")
        self.label_depth_1.setObjectName("label_depth_1")
        self.label_depth_2 = QtWidgets.QLabel(self.tab)
        self.label_depth_2.setGeometry(QtCore.QRect(350, 116, 128, 20))
        self.label_depth_2.setText("")
        self.label_depth_2.setObjectName("label_depth_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.button_stop_save = QtWidgets.QPushButton(self.tab_2)
        self.button_stop_save.setGeometry(QtCore.QRect(30, 320, 70, 25))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.button_stop_save.setFont(font)
        self.button_stop_save.setObjectName("button_stop_save")
        self.button_add_label = QtWidgets.QPushButton(self.tab_2)
        self.button_add_label.setGeometry(QtCore.QRect(110, 320, 70, 25))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.button_add_label.setFont(font)
        self.button_add_label.setObjectName("button_add_label")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 481, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_down.setText(_translate("MainWindow", "depth image"))
        self.button_save_picture.setText(_translate("MainWindow", "save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.button_stop_save.setText(_translate("MainWindow", "stop save"))
        self.button_add_label.setText(_translate("MainWindow", "add label"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
